# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: thiagoxvo/awscli-node-docker
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install dependencies
          command: yarn install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: Install AWS CLI
          command: |
            aws --version
        
      # run tests!
      - run: 
          name: Testing
          command: |
              npm test
              npm run test:lint
      - run:
          name: Deploy Push to S3 Bucket
          command: |
              aws deploy push --application-name API-Testing --s3-location s3://circle-ci-api/node.zip --ignore-hidden-files --region="us-east-2"
      - run:
          name: Create Deployment
          command: |
              aws deploy create-deployment --region="us-east-2" --application-name CodeDeploy_Test --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name CodeDeploy_Group --s3-location bucket=circle-ci-api,bundleType=zip,key=node.zip